[package]
edition = "2024"
name = "email_formatting"
publish = false
version = "0.1.0"

[dependencies]
askama = { workspace = true }
chrono = { workspace = true }
hmac = { workspace = true }
conation_service_urls = { path = "../conation_service_urls" }
macro_user_id = { package = "conation_user_id", path = "../conation_user_id" }
model_notifications = { path = "../model_notifications" }
notification = { path = "../notification" }
rootcause = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
