[package]
default-run = "notification_service"
edition = "2024"
name = "notification_service"
publish = false
version = "0.1.0"

[[bin]]
name = "notification_service"
path = "src/main.rs"

[[bin]]
name = "notification_service_openapi"
path = "src/openapi.rs"

[features]
default = ["push_notification_event_handler"]
local_queue = []
push_notification_event_handler = []

[dependencies]
anyhow = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
aws-sdk-sesv2 = { workspace = true }
aws-sdk-sns = { workspace = true }
aws-sdk-sqs = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
database_env_vars = { path = "../../crates/database_env_vars" }
email_formatting = { path = "../../crates/email_formatting" }
hmac = { workspace = true }
invite_email = { path = "../../crates/invite_email" }
http-body-util = { workspace = true }
itertools = { workspace = true }
last_online_tracker = { path = "../../crates/last_online_tracker" }
conation_auth = { path = "../../crates/conation_auth" }
conation_authorization = { path = "../../crates/conation_authorization" }
conation_aws_config = { path = "../../crates/conation_aws_config" }
conation_config = { path = "../../crates/conation_config" }
conation_cors = { path = "../../crates/conation_cors" }
conation_entrypoint = { path = "../../crates/conation_entrypoint" }
conation_env = { path = "../../crates/conation_env" }
conation_env_var = { path = "../../crates/conation_env_var" }
conation_event_broker = { path = "../../crates/conation_event_broker" }
conation_middleware = { path = "../../crates/conation_middleware", default-features = false }
conation_queues = { path = "../../crates/conation_queues" }
conation_tower_layers = { path = "../../crates/conation_tower_layers" }
conation_user_id = { path = "../../crates/conation_user_id" }
conation_uuid = { path = "../../crates/conation_uuid" }
mention_utils = { path = "../../crates/mention_utils" }
model = { path = "../../crates/model" }
model-entity = { path = "../../crates/model-entity" }
model-error-response = { path = "../../crates/model-error-response" }
model_file_type = { path = "../../crates/model_file_type" }
model_notifications = { path = "../../crates/model_notifications" }
model_user = { path = "../../crates/model_user" }
models_pagination = { path = "../../crates/models_pagination", features = [
  "axum",
] }
notification = { path = "../../crates/notification", features = ["axum"] }
notification_db_client = { path = "../../crates/notification_db_client" }
paste = { workspace = true }
rate_limit = { path = "../../crates/rate_limit" }
redis = { workspace = true }
regex = { workspace = true }
secretsmanager_client = { path = "../../crates/secretsmanager_client" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sns_client = { path = "../../crates/sns_client" }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["compression-gzip"] }
tracing = { workspace = true }
url = { workspace = true }
utoipa = { workspace = true, features = ["chrono"] }
utoipa-swagger-ui = { workspace = true }
uuid = { workspace = true }

conation_service_urls = { path = "../../crates/conation_service_urls" }
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

[dev-dependencies]
conation_auth = { path = "../../crates/conation_auth", features = ["testing"] }
