#!/usr/bin/env bash
# Point a macOS Tauri build at the Linux host that already runs the local
# Conation stack. No secrets. Safe to commit this script.
#
#   ./scripts/macos-connect-local-server.sh           # print connection story
#   ./scripts/macos-connect-local-server.sh --write   # write .env.desktop.local
#   ./scripts/macos-connect-local-server.sh --export  # eval "$(... --export)"
#   ./scripts/macos-connect-local-server.sh --check   # curl operator health
#   ./scripts/macos-connect-local-server.sh --macos-build
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${CONATION_DESKTOP_ENV_FILE:-$ROOT/.env.desktop.local}"
EXAMPLE_FILE="$ROOT/.env.desktop.local.example"

# Baked-in defaults for this Conation Linux server (Sep 2026).
DEFAULT_TAILSCALE_IP="100.89.19.82"
DEFAULT_PUBLIC_IP="173.212.222.197"
# Public IPv4:8090 and Tailscale TCP:8090 forward to conation-dev :24009.
# 127.0.0.1:8090 remains dynacat — never use loopback as the Mac origin.
DEFAULT_PROXY_PORT="8090"
DEFAULT_MAILPIT_PORT="24008"
DEFAULT_FUSIONAUTH_PORT="24005"

detect_tailscale_ip() {
  if command -v tailscale >/dev/null 2>&1; then
    tailscale ip -4 2>/dev/null | head -n1 || true
  fi
}

detect_public_ip() {
  local ip=""
  ip="$(ip -4 -o addr show dev eth0 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1 || true)"
  if [ -z "${ip}" ]; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  printf '%s' "${ip}"
}

load_local_env() {
  if [ -f "${ENV_FILE}" ]; then
    # shellcheck disable=SC1090
    set -a && source "${ENV_FILE}" && set +a
  elif [ -f "${EXAMPLE_FILE}" ]; then
    # shellcheck disable=SC1090
    set -a && source "${EXAMPLE_FILE}" && set +a
  fi
}

resolve_values() {
  load_local_env
  TAILSCALE_IP="${CONATION_TAILSCALE_IP:-$(detect_tailscale_ip)}"
  TAILSCALE_IP="${TAILSCALE_IP:-$DEFAULT_TAILSCALE_IP}"
  PUBLIC_IP="${CONATION_PUBLIC_IP:-$(detect_public_ip)}"
  PUBLIC_IP="${PUBLIC_IP:-$DEFAULT_PUBLIC_IP}"
  PROXY_PORT="${CONATION_PROXY_PORT:-$DEFAULT_PROXY_PORT}"
  MAILPIT_PORT="${CONATION_MAILPIT_PORT:-$DEFAULT_MAILPIT_PORT}"
  FUSIONAUTH_PORT="${CONATION_FUSIONAUTH_PORT:-$DEFAULT_FUSIONAUTH_PORT}"
  OPERATOR_ORIGIN="${CONATION_OPERATOR_ORIGIN:-http://${TAILSCALE_IP}:${PROXY_PORT}}"
  PUBLIC_ORIGIN="${CONATION_OPERATOR_ORIGIN_PUBLIC:-http://${PUBLIC_IP}:${PROXY_PORT}}"
  MAILPIT_URL="${CONATION_MAILPIT_URL:-http://${TAILSCALE_IP}:${MAILPIT_PORT}}"
  FUSIONAUTH_URL="${CONATION_FUSIONAUTH_URL:-http://${TAILSCALE_IP}:${FUSIONAUTH_PORT}}"
  PROFILE="${CONATION_CLIENT_PROFILE:-standalone}"
}

write_env() {
  resolve_values
  cat >"${ENV_FILE}" <<EOF
# Generated by scripts/macos-connect-local-server.sh — do not commit.
CONATION_CLIENT_PROFILE=${PROFILE}
CONATION_OPERATOR_ORIGIN=${OPERATOR_ORIGIN}
VITE_CONATION_OPERATOR_ORIGIN=${OPERATOR_ORIGIN}
CONATION_OPERATOR_ORIGIN_PUBLIC=${PUBLIC_ORIGIN}
CONATION_TAURI_HTTP_ORIGINS=${OPERATOR_ORIGIN},${PUBLIC_ORIGIN}
CONATION_MAILPIT_URL=${MAILPIT_URL}
CONATION_FUSIONAUTH_URL=${FUSIONAUTH_URL}
CONATION_TAILSCALE_IP=${TAILSCALE_IP}
CONATION_PUBLIC_IP=${PUBLIC_IP}
CONATION_PROXY_PORT=${PROXY_PORT}
EOF
  echo "wrote ${ENV_FILE}"
}

print_story() {
  resolve_values
  cat <<EOF
Conation operator (prefer Tailscale): ${OPERATOR_ORIGIN}
Public alternate:                     ${PUBLIC_ORIGIN}
Web app:                              ${OPERATOR_ORIGIN}/app
Auth health:                          ${OPERATOR_ORIGIN}/auth/health
Mailpit (login codes):                ${MAILPIT_URL}
FusionAuth:                           ${FUSIONAUTH_URL}
WS/sync:                              same origin, paths /websocket /connection-gateway /sync

Do not use http://127.0.0.1:8090 (dynacat). Direct operator: :24009.
Cursor Cloud stack alternate:         http://${TAILSCALE_IP}:23009

On the MacBook (Nix + Xcode CLT), same Tailscale tailnet:
  ./scripts/macos-connect-local-server.sh --write
  set -a && source .env.desktop.local && set +a
  cd apps/web && just tauri-build-local-stack
EOF
}

print_export() {
  resolve_values
  cat <<EOF
export CONATION_CLIENT_PROFILE='${PROFILE}'
export CONATION_OPERATOR_ORIGIN='${OPERATOR_ORIGIN}'
export VITE_CONATION_OPERATOR_ORIGIN='${OPERATOR_ORIGIN}'
export CONATION_TAURI_HTTP_ORIGINS='${OPERATOR_ORIGIN},${PUBLIC_ORIGIN}'
export CONATION_MAILPIT_URL='${MAILPIT_URL}'
export CONATION_FUSIONAUTH_URL='${FUSIONAUTH_URL}'
EOF
}

print_macos_build() {
  resolve_values
  cat <<EOF
# macOS only. Linux cannot produce the signed/notarized desktop app.
nix develop
bun install --frozen-lockfile
./scripts/macos-connect-local-server.sh --write
set -a && source .env.desktop.local && set +a
cd apps/web
just tauri-build-local-stack

# Dev loop (Vite on the Mac, API on the Linux server):
# CONATION_TAURI_APP_ENV=development \\
#   CONATION_OPERATOR_ORIGIN=${OPERATOR_ORIGIN} \\
#   VITE_CONATION_OPERATOR_ORIGIN=${OPERATOR_ORIGIN} \\
#   cargo tauri dev
EOF
}

check_health() {
  resolve_values
  local url="${OPERATOR_ORIGIN}/auth/health"
  local code
  code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 5 "${url}" || echo err)"
  echo "${code} ${url}"
  if [ "${code}" != "200" ]; then
    echo "operator origin is not healthy" >&2
    return 1
  fi
}

usage() {
  sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
}

cmd="${1:---print}"
case "${cmd}" in
  --print | -h | --help) print_story ;;
  --write) write_env ;;
  --export) print_export ;;
  --check) check_health ;;
  --macos-build) print_macos_build ;;
  *)
    usage >&2
    exit 2
    ;;
esac
