[package]
default-run = "search_processing_service"
edition = "2024"
name = "search_processing_service"
publish = false
version = "0.1.0"

[features]
default = ["processing", "service", "pdf"]
processing = [
  "dep:call",
  "dep:channels",
  "dep:chat",
  "dep:documents",
  "dep:email",
  "dep:kafka_util",
  "dep:conation_event_broker",
  "dep:conation_event_topics",
  "dep:models_properties",
  "dep:projects",
  "dep:properties",
  "dep:rdkafka",
  "dep:rootcause",
  "dep:tokio-retry",
]
service = [
  "dep:documents",
  "dep:conation_event_broker",
  "conation_db_client",
  "dep:models_properties",
  "dep:properties",
]
pdf = ["dep:pdfium-render"]

[[bin]]
name = "search_processing_service"
path = "src/main.rs"
required-features = ["processing", "service"]

[[bin]]
name = "search_processing_service_doppler_config"
path = "src/doppler_config.rs"

[dependencies]
anyhow = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-sdk-sqs = { workspace = true }
axum = { workspace = true }
call = { path = "../../crates/call", default-features = false, optional = true }
channels = { path = "../../crates/channels", default-features = false, optional = true }
chat = { path = "../../crates/chat", default-features = false, optional = true }
chrono = { workspace = true }
comms_db_client = { path = "../../crates/comms_db_client" }
email = { path = "../../crates/email", default-features = false, optional = true }
email_db_client = { path = "../../crates/email_db_client" }
futures = { workspace = true }
http-body-util = { workspace = true }
kafka_util = { path = "../../crates/kafka_util", optional = true }
lexical_client = { path = "../../crates/lexical_client" }
conation_auth = { path = "../../crates/conation_auth" }
conation_authorization = { path = "../../crates/conation_authorization" }
conation_aws_config = { path = "../../crates/conation_aws_config", features = ["s3"] }
conation_cors = { path = "../../crates/conation_cors" }
conation_config = { path = "../../crates/conation_config" }
conation_db_client = { path = "../../crates/conation_db_client", optional = true } # Make this optional
conation_entrypoint = { path = "../../crates/conation_entrypoint" }
conation_env = { path = "../../crates/conation_env" }
conation_env_var = { path = "../../crates/conation_env_var" }
calendar_events = { path = "../../crates/calendar_events" }
conation_event_broker = { path = "../../crates/conation_event_broker", default-features = false, features = [
  "outbound",
], optional = true }
conation_event_topics = { path = "../../crates/conation_event_topics", optional = true }
conation_queues = { path = "../../crates/conation_queues" }
conation_middleware = { path = "../../crates/conation_middleware", default-features = false }
conation_user_id = { path = "../../crates/conation_user_id" }
conation_uuid = { path = "../../crates/conation_uuid" }
mention_utils = { path = "../../crates/mention_utils" }
document_sub_type = { path = "../../crates/document_sub_type" }
documents = { path = "../../crates/documents", default-features = false, optional = true }
doppler-config = { workspace = true }
model = { path = "../../crates/model" }
s3_key = { path = "../../crates/s3_key" }
models_email = { path = "../../crates/models_email" }
model_file_type = { path = "../../crates/model_file_type" }
models_opensearch = { path = "../../crates/models_opensearch" }
models_properties = { path = "../../crates/models_properties", optional = true }
models_search = { path = "../../crates/models_search" }
nom = { workspace = true }
opensearch_client = { path = "../../crates/opensearch_client" }
ensure_exists = { path = "../../crates/ensure_exists", features = ["dynamodb"] }
pdfium-render = { workspace = true, optional = true }
properties = { path = "../../crates/properties", default-features = false, features = [
  "outbound",
], optional = true }
projects = { path = "../../crates/projects", default-features = false, optional = true }
rdkafka = { workspace = true, optional = true }
rootcause = { workspace = true, optional = true }
rust-embed = "8.6.0"
s3_client = { path = "../../crates/s3_client" }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
sqs_client = { path = "../../crates/sqs_client", default-features = false, features = [
  "search",
] }
sqs_worker = { path = "../../crates/sqs_worker" }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["signal", "sync", "time"] }
tokio-retry = { workspace = true, optional = true }
tokio-util = { workspace = true, features = ["rt"] }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
uuid = { workspace = true }

conation_service_urls = { path = "../../crates/conation_service_urls" }
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }
